### ISSUE TITLE
accessing metalsmith.json object properties

### ISSUE THREAD

**Issue by karneaud** [metalsmith/metalsmith#172]
Can we access the .json properties in other parts of the config so as to have them available to plugins

e.g.
```
{
"source":"path/to/files",
"plugins":
{
  "metalsmith-plugin":
{
path:"${source}/templates",
......
```

**Comment by Ajedi32** [comment]
No, that's not currently possible. Seems like it could maybe make for a good feature though...

**Comment by woodyrew** [comment]
From within a plugin, yes.

You're better off using metadata for making data available to plugins.

e.g.
`metalsmith.json`
```json
{
    "source": "source",
    "destination": "build",
    "metadata": {
        "path": "./templates"
    },
    "plugins": {
        "./my_plugin.js": {
            "some": "options"
          , "to"  : "pass to the plugin"
        }
    }
}
```


Here's the template I use when writing a new plugin:
`my_plugin.js`
```js
// Include debug to help with debugging.
var debug = require('debug')('metalsmith-name-of-my-plugin');


var my_plugin = function (options) {

    // Initialise plugin with options.
    // The plugin could need an instance of a library to process the data.

    return function (files, metalsmith, done) {

        // Metalsmith metadata usage:
        var metadata = metalsmith.metadata();
        var source_path = metalsmith.source();
        debug('metadata: %o', metadata);
        debug('source path: %o', source_path);

        // Loop through files
        Object.keys(files).forEach(function(file){
            debug('checking file: %s', file);
            var file_data = files[file];
        });

        // Errors should be reported if necessary
        /*if (has_issue) {
            // Allow metalsmith handle the error
            done(new Error('Explain the issue'));
        }*/

        // Call done() to tell Metalsmith it has finished.
        // This allows us to work asynchronously and call it when we are done.
        done();      
    };
};

// Expose the plugin
module.exports = my_plugin;

```


To see it in action:
```bash
$ DEBUG=* node_modules/.bin/metalsmith
```
or if you have metalsmith globally installed:
```bash
$ DEBUG=* metalsmith
```

`DEBUG=*` displays the debugging information.


This produces something like:
```bash
  metalsmith-name-of-my-plugin metadata: { path: './templates' } +0ms
  metalsmith-name-of-my-plugin source: '/home/woody/test/source' +3ms
  metalsmith-name-of-my-plugin checking file: ... +0ms
```

You can use the `metadata` and `source_path` within the plugin.

On a side note, generally you wouldn't want your `templates` directory within the `source` directory because they would get copied to the destination.  They're better located as a sibling to the `source` directory.

**Comment by karneaud** [comment]
@woodyrew not exactly what i was talking about. I believe in a grunt file you can access grunt variables from the objects root. Was indicating that metalsmith plugins can do the same with the metalsmith.son object being exposed to it thus using ${source} in the .json file itself is a place holder for the object's property I've seen it done in **metalsmith-watch** but its plugin based and not metalsmith core.... would be nice if it would be but writing it about it now it seems it might be more of a per plugin feature than metalsmith core....idk

**Comment by Ajedi32** [comment]
@karneaud Yeah, individual plugins can definitely implement this. Implementing this in the core CLI is also possible, but it would be a breaking change and I'm not sure whether it would be a good idea or not anyway.

There's also the possibility of configuring metalsmith programmatically instead of in a JSON file. (Just call `Metalsmith.build()` in a regular script,) That method gives you much more flexibility, but is also a bit more complex.

**Comment by woodyrew** [comment]
This is an interesting concept for the Metalsmith CLI however I don't feel this is something Metalsmith core should be extended to do. It can be achieved using Metalsmith within a `.js` file as it stands.
