### ISSUE TITLE
Selectively add multiple sources

### ISSUE THREAD

**Issue by Schoonology** [metalsmith/metalsmith#178]
I'm looking for advice on whether this belongs...
... in core, and I'll write a PR, or...
... in a plugin, and I'll write the plugin (something I've already done).

I have a project with _many_ top-level files and directories, including (perhaps obviously) `node_modules`. Of those, I want to use _two_ as the `source` for Metalsmith: `posts/` and `index.html`. I could use `.` as the `source` and manually ignore the rest (especially `node_modules`, which breaks everything), or (as I've done at the moment) I can use `posts` as the `source`, authoring a simple plugin to manually `.read()` the index, adding it to the `files` Object, etc.

Which of the two options is best? Am I missing a third, even better option?

**Comment by woodyrew** [comment]
Most use a structure like the following:
```bash
./ 
build/           - This will get generated by the build (destination)
node_modules/
src/             - This is where site content goes (source)
templates/       - For Handlebars (or templating system of your choice) templates
build.js         - Script that runs Metalsmith build
package.json
```

Where in `src/` you would have your `index.html` and `posts/`.

I hope this helps.

**Comment by Schoonology** [comment]
@woodyrew - Thanks for the update! I _did_ have a structure like that, but I'm looking to flatten the structure a little bit and remove the `src` directory.

**Comment by Ajedi32** [comment]
Hmm, well you could set `.` as the source directory and write a plugin to ignore everything but the two files/directories you are interested in. That seems very inefficient though, since you'd be reading the entire contents of `node_modules`, etc into memory then immediately discarding it.

As-is, either of the two approaches you mentioned in the original post would probably be fine. Personally, I like the "manually ignore everything in the project directory that's not source" approach since it seems more semantically correct (e.g. you actually *are* trying to make `.` your source directory, from what I understand) but functionally speaking I think either approach would be acceptable.

**Comment by webketje** [comment]
Metalsmith 2.4 will make this rather unconventional approach possible nevertheless, as `ignore` will remove the files before they are read into memory.
