### ISSUE TITLE
Switch to VFile for file management

### ISSUE THREAD

**Issue by RobLoach** [metalsmith/metalsmith#196]
https://github.com/wooorm/vfile

Provides an interface for managing files virtually.

**Comment by wooorm** [comment]
:+1: Ping me if I can help. An alternative is of course Vinyl, I’ve outlined the difference in [VFile’s readme](https://github.com/wooorm/vfile#readme), but let me know if I can explain more in-depth.

**Comment by RobLoach** [comment]
> VFile is different from (the excellent :+1:) vinyl in that it does not include file-system or node-only functionality. No buffers, streams, or stats.

Ah, I believe Metalsmith requires Buffers. So maybe Vinyl is the way to go? Could we extend VFile to allow for Buffers?

**Comment by wooorm** [comment]
Yup, I would support the switch from `file.content`, which is currently a string, to buffer.

In essence, that would mean `file.content.toString(file.encoding)` (`file.encoding` not yet existing) should be used everywhere.

**Comment by Ajedi32** [comment]
So as I understand it, aside from adding some nice convenience methods to the API, this would also address #58.

On the other hand, it also has the downsides discussed in #58 as well, mainly a significant loss of simplicity in Metalsmith's API. Additionally, it would also be a major breaking change, with all plugins having to be rewritten to support the new API (or at the very least, a compatibility system needing to be put in place to run older plugins).

I guess I'm just not sure I see the benefit of a change like this. What does it get us?

**Comment by Ajedi32** [comment]
I've thought about this a bit more, and while I still don't think "switching to VFile" would be a good move for Metalsmith (both because it totally breaks backwards compatibility, and because it complicates the currently dead-simple files object), it seems totally feasible to provide an object that wraps the files object and provides a VFiles-like interface to it.

If you want to do something like that, I say go for it! It doesn't even need to be in the Metalsmith core, just a library that plugins can use. You might not be able to implement all the features of VFile, but you could probably get about 80% of them. Thoughts?

**Comment by woodyrew** [comment]
@Ajedi32 I agree, I don't see the benefits and a simple plugin could provide filename tracking information if that were a requirement for someone.
