### ISSUE TITLE
Proposal: Split out metalsmith CLI into metalsmith-cli project

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith#205]
Just like how grunt has both [`grunt`](https://github.com/gruntjs/grunt) and [`grunt-cli`](https://github.com/gruntjs/grunt-cli), and gulp has [`gulp`](https://github.com/gulpjs/gulp) and [`gulp-cli`](https://github.com/gulpjs/gulp-cli), I'm starting to think it might be a good idea to break metalsmith out into `metalsmith` and `metalsmith-cli`.

This would help keep the core minimal, while allowing us to add nice features like `metalsmith init blog` to the CLI.

**Comment by Ajedi32** [comment]
Related to #153

**Comment by woodyrew** [comment]
I like this idea. Would have to be a major version bump. A good time to switch to an array for the CLI too so plugins can be ordered and reused #129.

Would this cause any issue at Segment @lambtron?

**Comment by listepo** [comment]
+1

**Comment by Ajedi32** [comment]
@woodyrew Switching to an array for plugins in metalsmith.json isn't actually a breaking change. As noted in #129, you can actually already use arrays with the CLI, it's just not documented. (So we just need to update the documentation to recommend using an array instead of an object.)

But yes, extracting `metalsmith-cli` from the core like this is definitely a breaking change, and I agree it makes sense to group together as many backwards-incompatible changes as possible so we can release them all as Metalsmith 3.0 instead of having to release 3.0 then 4.0, etc.

Other breaking changes we should look at:

* #196 - not sure I agree with this one, but it *would* definitely be a breaking change if we decide to do it
* #157, #169 - Currently closed as wontfix, but I'd actually like to revisit this one. It's quite similar to this issue (extracting frontmatter parsing vs extracting the cli), and I don't feel like my arguments in favor of it were ever really addressed
* #58 - Seems likely that any changes meant to address this would likely be backwards-incompatible. No idea what form they would take (if any), but it's at least worth investigating prior to 3.0.

**Comment by woodyrew** [comment]
# File handling
For #58: I've not experienced any problems with filenames. Is it an education issue (see method below) or have I not come across the problem? Through the Metalsmith pipeline, a plugin shouldn't need to know the original source filename or any of the intermediary steps. It should deal with the file state as it is at that point in time.

What benefit would #196 provide? If it's the ability to handle a greater volume of files then maybe it would be worth doing.

## File handling - the method:
1. Add a `slug` value or use a `make_slug` function to create a unique page identifier.
2. Use `metalsmith-collections` to group nested pages, e.g. blog entries, pages etc.
3. Use permalinks to place them in the correct location according to the collection and slug.

Within any file/template, you know which collection it belongs to and the slug so the url can be generated from that.

**Comment by Ajedi32** [comment]
@woodyrew I'd prefer to move those discussions to their respective issues, but I generally agree with you. I'm not actually sure what underlying problems #58 and #196 are intended to address.

**Comment by ianstormtaylor** [comment]
Personally, `metalsmith init` sounds like feature creep, and scaffolding in general isn't the greatest. It seems smarter to gauge whether more CLI extensions are really needed first, before deciding to split out the metalsmith cli just because it's in vogue. (In general I think Grunt/Gulp aren't really beacons of "doing things right".)

Trying to smooth out the adoption curve is a great idea. I think there are lots of places to do that without actually adding or changing any code. It's more of a communication problem, with a few bugs/etc. thrown in.

**Comment by Ajedi32** [comment]
> It seems smarter to gauge whether more CLI extensions are really needed first, before deciding to split out the metalsmith cli just because it's in vogue.

Correct. I'm only making this proposal in anticipation of new features being added to the CLI making it more than just a thin wrapper over the Metalsmith API. If the CLI's feature set is not expanded, this change is unnecessary.

> Personally, `metalsmith init` sounds like feature creep, and scaffolding in general isn't the greatest.

Care to expand on that? I think scaffolding is an excellent way to help new users get started with tools like Metalsmith.

I agree it wouldn't make much sense to put development tools like that in the Metalsmith core though, which is why I'm proposing extracting the CLI. Separation of concerns. The Metalsmith core should be concerned with providing a simple API for running a set of files through a series of Metalsmith plugins, whereas the CLI should be concerned with helping users build projects using Metalsmith. That's the way I see it anyway.

> Trying to smooth out the adoption curve is a great idea. I think there are lots of places to do that without actually adding or changing any code. It's more of a communication problem, with a few bugs/etc. thrown in.

How so? Any specific things you think could be done which would negate the need for a scaffolding system?

**Comment by ianstormtaylor** [comment]
I don't see scaffolding new projects as the responsibility of Metalsmith, whether in the Javascript API or in the CLI. Scaffolding itself is a huge task to take on, and better solved by tools that aren't attached to any specific library, Javascript or otherwise. For example, [Khaos](https://github.com/segmentio/khaos), [Slush](https://github.com/slushjs/slush) or [Yeoman](https://github.com/yeoman/yo).

If someone wants to use a scaffolder to get started, we can easily link to the scaffolding templates in a Getting Started section in the Readme or Wiki. That way they have the option, without having to add anything new to core. And as a bonus: they don't need to learn an entirely new scaffolding API, and they can easily write their own templates if they find themselves with different basic needs.

**Comment by Ajedi32** [comment]
I agree that there are certainly already projects that do scaffolding well and there's no need to reinvent the wheel, but I do think there is potentially some value in bundling that sort of functionality in the metalsmith CLI (even if the actual logic is mostly outsourced to a third party library).

I guess how useful that is really depends on how well we're able to cover this using _just_ documentation, with no additional tools. If we can get for example, installing Khaos as part of our quick-start guide, maybe that _would_ be sufficiently simple for new users unfamiliar with Metalsmith to use...

**Comment by woodyrew** [comment]
I think scaffolding is another subject to be discussed. Personally, creating a Yeoman builder would be my thought but I've not looked into any others recently.

To move this forward however, there are a couple of steps involved from what I see. 

- [ ] Create a metalsmith-cli repo.
- [ ] Take across all the existing functionality and tests.
- [ ] Migrate issues to the new repository pertaining to the CLI, reference new issue and close on metalsmith repo.
- [ ] Update Metalsmith docs and metalsmith.io.
- [ ] Once all the previous steps have been complete, the CLI can be removed from Metalsmith and major version bumped.

Thumb up if you're happy with this approach and comment if you're not and edit if I've missed anything.
@ianstormtaylor @Ajedi32 @lambtron

**Comment by woodyrew** [comment]
*Repository* &mdash; https://github.com/metalsmith/metalsmith-cli
I've applied Babel and ESLint (with the AirBnB style guide as a base) to the codebase.

I'll aim to migrate the CLI issues over in the next week.

**Comment by ianstormtaylor** [comment]
I'm personally still -1, but I don't use Metalsmith anymore, so I'm fine with whoever maintaining Metalsmith making the decision. But from my perspective we still haven't answered the question:

> Why does the CLI need to be separated out into a separate repository? 

It seems like so far it's just been "because other tools did it" (and I'd argue that those tools aren't great, so why blindly copy their decisions), and "because it lets us add scaffolding" which I don't think is a good idea. There's also the option to add other functionality, but nothing concrete yet. It feels like the better solution would be to continue developing whatever features are necessary to be added to the CLI, and split it out when it actually becomes hard to manage.

Especially since there are obvious cons to separating the two, namely:

- An unnecessary breaking change for users right now.
- A more confusing issue-submitting experience.
- A more confusing installation experience.
- A slightly harder development experience for releases / shared code.

For what gain?

**Comment by Ajedi32** [comment]
> For what gain?

**Comment by woodyrew** [comment]
Sorry for the long response but I wanted to address all the points. I agree, the motivation shouldn't be because "_other tools have done it_" or "_let's add scaffolding_".

> Why does the CLI need to be separated out into a separate repository?

It doesn't _need_ to be separated out, but that's not to say there's not reason to do it. The Unix philosophy of minimal and modular, making utilities do one job but do it really well has a lot of strength.

90% of the consumers of Metalsmith use the core project, it seems pointless to include the CLI also when it's not needed.

I also don't think there should be scaffolding in Metalsmith either however the same could be said for the CLI. If we do have these, should they be in core?

### _Cons_
> An unnecessary breaking change for users right now.

We're coming up to a major version release with [various other features](https://github.com/metalsmith/metalsmith/milestone/2) I don't see how incorporating this is any different.

> A more confusing issue-submitting experience.

Issues on the CLI can be escalated to core if necessary. (e.g. `This issue is dependant upon metalsmith/metalsmith#{issue number}`)

> A more confusing installation experience.

- `npm i -S metalsmith` or `npm i -S metalsmith-cli` (or the latter with `-g` for global if someone wished to do that).
- It's probably more confusing for Metalsmith to provide both APIs within the same module at the moment.

> A slightly harder development experience for releases / shared code.

- There won't be any shared code, the CLI requires Metalsmith core and provides a CLI API.
- Core and the CLI can be improved independently, the CLI can choose when a core release is relevant to warrant an upgrade and a version bump.

> For what gain?

A good question. Apart from what's already been discussed and [Sindre Sorhus' rational on splitting CLI's from their core modules](https://github.com/sindresorhus/ama/issues/17#issuecomment-117860283), the gains will be for consuming Metalsmith rather than developing it.

We could always merge it back in if developing them separately actually becomes hard to manage.

**Comment by ianstormtaylor** [comment]
Fair enough, those are good arguments @woodyrew. I'm convinced 👍

**Comment by ijy** [comment]
@ianstormtaylor How come you don't use Metalsmith anymore? Just a shift of focus?

**Comment by ianstormtaylor** [comment]
@ijy yup, exactly! Not Metalsmith's fault. If I was working on things that needed a static-site generator I'd definitely still use it, I just don't work with its code on a daily basis anymore, or do any of the maintenance work.

**Comment by hollowdoor** [comment]
@woodyrew @Ajedi32 I think internal scaffolding should be considered by any project that has a cli, and consumes a text config file. Being prompted like with `npm init` is like having some extra documentation. 

Heck even `ava` has `ava --init`, and one of the contributors to yeoman is the creator of `ava`. Though ava's scaffold only fills out one line in a `package.json`, but still it accepts config parameters on `--init`. Any third party scaffold tool is still another dependency. That's my opinion anyway.

[plop](https://www.npmjs.com/package/plop) might be a library worth looking at to make it easier.

**Comment by webketje** [comment]
I did the exercise of splitting MS into a separate CLI. TBH it makes little difference and atm the CLI has such a small footprint (single command, single extra dependency) that it will create more overhead than added value at this point so I'm closing this issue now.
