### ISSUE TITLE
Make ignore globs match paths relative to the source directory (instead of matching absolute paths)

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith#206]
As I understand it, currently Metalsmith's `.ignore` function matches files and directories as absolute paths, due to the way it delegates to `recursive-readdir`. (See jergason/recursive-readdir#23) This can lead to unintuitive behavior.

For example, ignoring `**/some_dir/**/*.source` will ignore all `*.source` directories in the project (not just the ones under `some_dir`) if metalsmith's source directory is a descendant of a directory named `some_dir`.

As another example, ignoring `some_dir/**/*.source` (not prefixed with `**/`) actually ignores nothing, because it's matching against an absolute path. Similarly, so does `./some_dir`. (Which I'd expect to ignore `some_dir` in the root of the project, whereas ignoring `some_dir` would ignore all files and directories named `some_dir` anywhere in the project.)

We should fix the ignore system to ensure ignores behave in an intuitive way in all cases.

**Comment by Steef435** [comment]
Is there (still) interest in a "fix" for this? What about prepending all arguments with the source directory unless they start with '/'?

If not, what do you think of specifying that the string argument(s) should be full paths in the documentation? That was unclear for me.

Merry Christmas!

**Comment by Ajedi32** [comment]
> What about prepending all arguments with the source directory unless they start with '/'?

Yeah, that seems like a reasonable solution. This would be a breaking change though, so once we do get around to fixing this I want to group it with a few other breaking changes in order to minimise impact on end-users. (Prevent multiple "breaking" updates in a row.)

**Comment by Steef435** [comment]
I started working on this, then I suddenly realized that this will probably not work very well on Windows systems. It would be impossible to ignore by absolute path. Is that an issue?

**Comment by leviwheatcroft** [comment]
The native path lib has [isAbsolute()](https://nodejs.org/api/path.html#path_path_isabsolute_path) which should be reliable.

**Comment by webketje** [comment]
`ignore` accepts both *paths* and *globs*.
With 4eb118440a6e15a0312d10eb4c4e3bfcaf200eff I threw out recursive-readdir in favor of an own implementation.
This effectively makes *the glob patterns **only** match relative to the `Metalsmith.source`*.

Effectively in Metalsmith 2.4.0

- `./some_dir` will only match `src/some_dir` and descendants
- `some_dir` will only match `src/some_dir` and descendants (it is not a glob pattern because none of these chars are present:  `?*[`, and hence will resolve to the same as  `./some_dir` using `path.relative`)
- `**/some_dir/**` will match `src/some_dir` and descendants as well as `src/other/some_dir` and descendants

cc @Ajedi32

**Comment by Ajedi32** [comment]
Seems good to me. 👍

**Comment by webketje** [comment]
@Ajedi32 thanks a lot for taking the time to give some feedback (also on the commit),
the blessing of the other / ex-maintainers means a lot to me.
