### ISSUE TITLE
Metalsmith silently ignores syntax errors in frontmatter

### ISSUE THREAD

**Issue by woodyrew** [metalsmith/metalsmith#226]
When you have invalid frontmatter (YAML in my case), Metalsmith doesn't report the issue. I think [js-yaml](https://github.com/nodeca/js-yaml) reports the errors but I'm not sure if it's Metalsmith or [gray-matter](https://github.com/jonschlinkert/gray-matter) gobbling the errors.

Frontmatter variables are available up until the erroneous YAML.

e.g.

```

---
ok_var: 'Here'
not_ok: (problem)

---
```

`ok_var` is ok but `not_ok` and any variables after haven't been processed and are therefore not available.

No error is produced even with `DEBUG=* node my_build.js`.

**Comment by Ajedi32** [comment]
Seems this is intentional behavior on the part of `gray-matter`: https://github.com/jonschlinkert/gray-matter/blob/2.0.1/lib/parsers.js#L44-L50

No idea if we want to change the defaults or not. (I'd argue we probably do.) In the meantime you can get this behavior using [`metalsmith-matters`](https://github.com/Ajedi32/metalsmith-matters) like so:

```javascript
var frontmatter = require('metalsmith-matters');
 
Metalsmith(__dirname)
  .frontmatter(false)
  .use(frontmatter({
    strict: true
  }))
  .use(/* Other plugins... */)
  .build(function(err) {
    if (err) throw err;
  });
```

**Comment by woodyrew** [comment]
I agree, I don't think it should be silent. I thought it might be `gray-matter` rather than `metalsmith`.

I'll use `metalsmith-matters` for now but I think there should be a switch for the built-in `.frontmatter()` method.

**Comment by Ajedi32** [comment]
Yeah, I suppose we could add the ability to set gray-matter options to the metalsmith core. Personally though I'd still prefer to just extract that system from Metalsmith entirely instead of expanding its functionality even further. (#169)

That's kinda a separate issue though. The solution to this specific issue would be to enable strict mode by default.

**Comment by woodyrew** [comment]
Closing as this has a solution.

**Comment by Ajedi32** [comment]
Huh? What do you mean by that? Seems like a bad idea for Metalsmith to silently ignore errors like this by default.

**Comment by woodyrew** [comment]
Sorry, yup - you're right. Defaulting to strict should be a major version change if we do that. I'm happy to do it and write the missing tests.

Default to strict but allow options to be passed through to _gray-matter_.
`.frontmatter(false)` to turn off in the same way it is now.
`.frontmatter({strict: false})` to make it sloppy.
It's not the nicest but it's backwards compatible.

**Comment by webketje** [comment]
When rethinking this, it seems like a no-brainer to me.
No one would intentionally want to ignore errors in the YAML front-matter, so setting `strict: true` has to be considered a bugfix rather than a breaking change and can be included in a minor release. It does look interesting to give the possibility to tweak gray-matter's config (custom delimiters, eval: true)
