### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by keithws** [metalsmith/metalsmith#243]
The last release, 2.1.0, was in September 2015. It's almost a year later and 50+ commits later and still no new releases. Why?

**Comment by Ajedi32** [comment]
Mostly because there just hasn't been a lot of new development on Metalsmith lately. Those 50+ commits are largely updates to the Metalsmith documentation, tests, and other things that don't really require a new release to take effect. For unreleased changes that actually affect Metalsmith's users, see [the CHANGELOG](https://github.com/metalsmith/metalsmith/blob/master/CHANGELOG.md#unreleased).

I can't really speak as to why development has slowed, since despite my current association with the project I've never really been the primary contributor in terms of actual code. Once I get some free time to work on Metalsmith I do have some changes I'd like to make, but for now my involvement has mostly been limited to responding to questions in the issue tracker and merging minor changes that come in PRs.

**Comment by keithws** [comment]
Thank you for your candid response. I am evaluating static site generators for a project with over 2500 pages. So, I want a project that is mature and stable but isn't dead. When it comes to static site generators built with node.js, metalsmith does seem to be one of the most mature and highly rated, but I'm concerned the original author has abandoned this project and no one is taking his place. Is anyone that uses metalsmith concerned or does it do everything you need as-is?

**Comment by Ajedi32** [comment]
@keithws Metalsmith itself is pretty simple, and doesn't contain a lot of functionality in core. Most of the functionality of Metalsmith is implemented through plugins, which are maintained independently of Metalsmith itself. Because of that I'm actually not too worried about a lack of maintenance becoming a major issue for Metalsmith.

The fact that Metalsmith is open source and the rather small size of the core also makes me less concerned about the project dying, as I'm pretty confident I could maintain Metalsmith myself if need be. The whole thing is literally just 345 lines: https://github.com/metalsmith/metalsmith/blob/2.1.0/lib/index.js (Admitedly, the dependencies do add a bit of complexity, but I think I've mostly wrapped my head around those at this point.)

**Comment by woodyrew** [comment]
@keithws As Ajedi32 said, there's not much to go wrong with Metalsmith and the power is provided to the excellent plugin system. I work with Metalsmith full time on relatively large codebases. The community Slack channel is pretty active for support too if needed.

**Comment by keithws** [comment]
Thank you for sharing. We have decided to build a proof-of-concept with metalsmith.

**Comment by keithws** [comment]
One last question, any tips for working with large builds? Recommended plugins?

**Comment by Ajedi32** [comment]
I haven't had any experience with large builds as of yet, but for some example configurations you can use you could look in [`examples/`](https://github.com/metalsmith/metalsmith/tree/master/examples).

**Comment by woodyrew** [comment]
@keithws I've worked on some large builds with Metalsmith. If you can split your build up into logical sections that don't need to know about each other that's helpful. If they do need to know about each other you can always pass metadata around to fill the gaps.

The main plugins I use are:

- `metalsmith-default-values`
- `metalsmith-in-place`
- `metalsmith-layouts`
- `metalsmith-markdown`
- `metalsmith-permalinks`

The rest are generally semi-custom to the task in hand.

If you've got any more questions, join the Slack chat room: http://metalsmith-slack.herokuapp.com/
