### ISSUE TITLE
Convert make tasks to be npm scripts

### ISSUE THREAD

**Issue by woodyrew** [metalsmith/metalsmith#260]
Currently, we have make to compile, run tests etc. This doesn't work on Windows ([without installing make](https://www.google.cl/search?q=make%20for%20windows)).
npm scripts are more than capable of performing the same tasks without the dependency.

**Comment by winniehell** [comment]
I'd like to do this but I am unsure how to plug the [`v8-options` part] into the `package.json`. Any idea?

[`v8-options` part]: https://github.com/metalsmith/metalsmith/blob/master/Makefile#L4

**Comment by Purring** [comment]
if it's supposed to run on windows, I'm not too sure if they would even have grep or cut installed either.

**Comment by Ajedi32** [comment]
Yeah, part of the reason we have been using `make` up to this point is because of that functionality. Those flags are only needed for Node 0.12.x compatibility though, and that version of Node [will be unsupported as of December](https://raw.githubusercontent.com/nodejs/LTS/6f24db9eb87727ab3b4903b01f5e587504e7ddf7/schedule.png) (see also #231), so if we're ready to start working on the next major release we could just drop those flags entirely...
