### ISSUE TITLE
Should CSS be included with plugins?

### ISSUE THREAD

**Issue by hollowdoor** [metalsmith/metalsmith#272]
I'm getting ready to make a plugin for metalsmith.

What I'm wondering is -- should a plugin include CSS? If so then how should it be included?

Should it be injected with some other plugin like `metalsmith-layouts`, added as a style tag in the html, or leave it up to the consumer to decide if they want it styled? What's the best advice?

The reason I ask is because my plugin is going to add html to each page. In a sense the html output might not be exactly what would be expected as presented without styles. I'm considering leaving the styling to the user, but I'm unsure at this point.

**Comment by Ajedi32** [comment]
I guess it depends on how you expect people to use your plugin. Are they looking for some sort of integrated solution that they can enable and expect it to "just work"? Or do they want a modular solution that they can customize precisely to suit their exact needs.

Personally I'd lean towards the later since that's a bit closer to the philosophy of Metalsmith itself, but you probably know what you're aiming to build better than I do.

General advice: build your plugin, use it in your own site, see what works and what doesn't, and iterate until you're satisfied with it.

**Comment by hollowdoor** [comment]
From what you're telling me it seems like you're saying do whatever you want. :)

I'm thinking I'll just leave it as bare HTML. In the documentation I'll describe all the CSS classes, and elements that can be styled. It might be better to start slim any way, and grow it. Verses starting big, and having to trim.
