### ISSUE TITLE
Proposal for functional API variant

### ISSUE THREAD

**Issue by jmatsushita** [metalsmith/metalsmith#287]
Hi there,

It would be great to allow dealing with metalsmith plugins in a more functional way by allowing plugins to return a modified `files` object (and/or global `metadata` object) rather than modifying it in place.

This would allow this type of concise syntax with arrow functions and the lodash pickBy function for the [example draft plugin](https://github.com/segmentio/metalsmith/blob/master/examples/drafts-plugin/index.js#L14-L20) for instance:
```
var pickBy = require('lodash/pickBy')

function plugin(){
  return function(files){
    return pickBy(files, file => file.draft);
  };
}
```

I think this could be made a sufficiently backward compatible modification (although I imagine not all plugins return null currently):
 - if the plugin return null then assume the files array and metadata object are globally mutated
 - if the plugin returns an Object of the form `{ files: Array, metadata: Object}` then assume that both the files array and metadata object are passed in a functional style.
 - if the plugin returns another Oject then assume the files Object is passed in a functional style.
 - if the plugin is async, then do the same thing with the result passed to the callback.

Of course it's already possible to add a bit of boilerplate to plugins to do the same thing like so:
```
var pickBy = require('lodash/pickBy')

function plugin(){
  return function(files){
    var newFiles = pickBy(files, file => file.draft);
    Object.keys(files).forEach(key => {
      if (newFiles[key]) {
        files[key] = newFiles[key];
      } else {
        delete files[key];
      }
    });
  };
}
```

But it would be great if the API encouraged a more modern approach!

Let me know what you think!

Jun

**Comment by jmatsushita** [comment]
Just ran into a PR - https://github.com/Waxolunist/metalsmith-writemetadata/pull/3 - which would be addressed by this approach which would avoid mutating `files`.

**Comment by Ajedi32** [comment]
Seems like a decent little convenience for cases where you might want to write your plugins in a functional style.

I don't really see how this would have addressed `Waxolunist/metalsmith-writemetadata#3` though. I believe the issue there isn't that `files` is being mutated (in fact, mutating `files` is completely standard behavior for plugins) but that it's being mutated to convert the `contents` property to a string (which is not a valid state for the `contents` property to be in).

Also worth noting that it'd be pretty easy to write a function that implements similar behavior without requiring any changes to the Metalsmith core. Quick example (probably needs more work to account for metadata changes, callbacks, etc):

```javascript
function functionalPlugin(func) {
  return (files) => {
    let newFiles = func(files)
    Object.keys(files).forEach(key => {
      if (newFiles.hasOwnProperty(key)) {
        files[key] = newFiles[key]
      } else {
        delete files[key]
      }
    }
  }
}
```

Then you can just write your functional plugin the way you described in this issue and convert it to one that works with Metalsmith using:

```javascript
myFunctionalPlugin = functionalPlugin(myFunctionalPlugin)
```

**Comment by MorganConrad** [comment]
I like the idea, but bullet 2 has an issue: where to put the results from an **array** "back into" the files **object**.  Therefore, suggest that bullets 2 & 3 be merged for a simpler API, and become:
 - if the plugin returns an Object of the form { files: **Object**, metadata: Object }...

**Comment by leviwheatcroft** [comment]
The PR mentioned above `Waxolunist/metalsmith-writemetadata#3` is being misunderstood I think. writemetadata just scrapes data from the files structure and writes it to disk as json. Before that PR, it was changing the `contents` properties on each file to be a string instead of a buffer, when it should have just read the buffer and left the files as they were. So I don't think this kind of functional style is really relevant.

I don't really see a problem with introducing this behaviour, given that the existing behaviour can be maintained.

**Comment by MorganConrad** [comment]
It's not brilliant, but here's my simplistic "functional" plugin:  https://github.com/MorganConrad/metalsmith-functional

**Comment by webketje** [comment]
Although there is indeed a trend towards *immutability* (cf Redux a.o.), metalsmith functions as a middleware pipeline rather than a store to which actions are dispatched and state diffed. Express.js middleware also mutates the request object and request listeners take advantage of pass-by-reference + it has a lower memory footprint.
Finally, having plugins return a new copy of the files object is bound to introduce issues with deep cloning and existing plugins that work based on pass-by-reference (e.g. metalsmith-collections) and would make the API more complex to understand. Closing
