### ISSUE TITLE
Amplify Build Error when trying to execute metalsmith-migrated-plugins.js

### ISSUE THREAD

**Issue by antonio-masotti** [metalsmith/metalsmith#373]
**Description**
In version 2.5.0 the metalsmith-migrated-plugins.js was added. Unfortunately AWS Amplify seems to have a problem with executing the postinstall. 

Any idea what is causing this and how to solve? Thanks in advance!

** Error message**

![image](https://user-images.githubusercontent.com/91308510/173335385-769653bf-b7a3-44b1-8da1-8307a64242f6.png)

**Environment**

- OS: : Amazon Linux 2
- Node version: 16.14.0
- Npm version: 8.12.0
- Amplify/cli : 8.4.0

**Reproducing the bug**
deploy on Amplify and let run `npm install -g @quasar/cli` (metalsmith is a dependency of @quasar/cli)

**Comment by webketje** [comment]
It looks like the OS doesn't have NodeJS in the executables environment variable `PATH`, or it is differently named (one of the lines says `sh: node: command not found`). But even so, this should not happen so I will release a bugfix that will make sure the command never hard-fails.

If you have access to the CLI (I suppose this is in a CI run), try running `which node` to confirm. Also possible perhaps is that it is available as  `nodejs`. A quickfix can be done by finding the path of the Node binary on the OS and adding it to PATH, eg. run sth like

```bash
export PATH=$PATH;/path/to/node/binary
```

**Comment by antonio-masotti** [comment]
@webketje Thanks a lot for the quick replay.

`node` is there and is working. If I run `which node` or `node -v` I get the correct output. It seems to me that the `metalsmith-migrated-plugins.js` is not found for some reasons when called while installing `npm i -g @quasar/cli`.

I will however also try by explicitely exporting the Node path.

**Comment by delbug** [comment]
me too 
-------
Cannot find module '/root/.nvm/versions/node/v14.8.0/lib/node_modules/vue-cli/node_modules/metalsmith/metalsmith-migrated-plugins.js'

**Comment by webketje** [comment]
@antonio-masotti please report back if you found the cause for this issue. I cannot reproduce it locally
The only approaches I have are appending `|| 0`  after the postinstall script so that it always sends back a 0 code (basically ignoring the error) or putting the script in a bin with a shebang instructing the shell to use node


@delbug are you using a very outdated version of the vue-cli? (eg 2.5.0) Newer versions do not use metalsmith.

**Comment by webketje** [comment]
Further observations:
- The postinstall script somehow runs in a different shell than the main shell (eg dash instead of bash) which does not have node in its PATH env var. In that case, try to run `npm config set scripts-prepend-node-path true` before doing `npm i -g @quasar/cli`. 
- A solution that works if no other dependencies do a post-install: `npm config set ignore-scripts true`
- In @delbug's case it looks as if the NodeJS version used in the postinstall script is different from the one used to npm install vue-cli. Make sure you didn't accidentally switch Node versions with nvm and installed from a separate terminal
