### ISSUE TITLE
Debug not working as expected?

### ISSUE THREAD

**Issue by jtlapp** [metalsmith/metalsmith#383]
Hello. I had to trace into metalsmith to find out why it was erroring because this is all my debug log showed:

```
  [36;1m@metalsmith/markdown [0mchecking file: index.md [36m+0ms[0m
```

The trace revealed that my `*.md` was missing a `layout` field. Here's the `.cjs` block whose message seems to be lost:

```js
  if (!layout) {
    debug(`validation failed, ${filename} does not have a layout set`); // traces to here
    return false;
  }
```

I've not been able to figure out how to get the debug line to show up in the log. Here's what I've tried:

```js
const Metalsmith  = require('metalsmith')
const layouts     = require('@metalsmith/layouts')
const markdown    = require('@metalsmith/markdown')

Metalsmith(__dirname)
  .env({
    NAME: process.env.NODE_ENV,
    DEBUG: true, // also tried "*" and "@metalsmith/*"
    DEBUG_LOG: 'metalsmith.log'
  })
  .metadata({
    /* ... */,
    generatorname: "Metalsmith",
    generatorurl: "https://metalsmith.io/"
  })
  .source('./content')
  .destination('./build')
  .use(markdown())
  .use(layouts({
    engine: "nunjucks"
  }))
  .build(function(err) {
    if (err) throw err;
  });
```

What should I be doing differently? Thanks for any help you can provide!

**Comment by webketje** [comment]
@jtlapp welcome and I'm really sorry for the inconvenience. All of these will work as you correctly assumed:

> true, // also tried "*" and "@metalsmith/*"

Only the plugins implementing `metalsmith@2.5.0+`'s `metalsmith.debug` debuggers will log to the MS log.
Unfortunately there are still some core plugins for which this is not the case yet (like @metalsmith/layouts). Many non-updated third-party plugins will have this issue too. In order to get all log output for those plugins not using `metalsmith.debug` but their own, repeat it as env var, eg:

````
DEBUG=@metalsmith/* node ./metalsmith.js
````
To align both you can then do in the build:

```
.env('DEBUG', process.env.DEBUG)
```

There's more info in the release post about the debug method but it hasn't made it into permanent docs yet (you may want to use DEBUG only, without DEBUG_LOG): https://metalsmith.io/news/2022-06-10/metalsmith-2.5-released/#highlights

**Comment by jtlapp** [comment]
Thank you! To get this to work, I had to do both of these:

```js
  .env({
    DEBUG: true
  })
```

```
DEBUG=@metalsmith/* node ./metalsmith.js
```
