### ISSUE TITLE
Ordinary html file not recognized as utf-8 encoded, stopping gray-matter to parse YAML

### ISSUE THREAD

**Issue by gargi91** [metalsmith/metalsmith#387]
I have a use case, where I am generating an api reference docs (.html file) using another library ([redoc](https://redocly.com/docs/cli/)). The YAML frontmatter is appended to the beginning of the file correctly, but I was unable to parse the frontmatter. It was failing at [this](https://github.com/metalsmith/metalsmith/blob/3a93270879ac8c01d114eccb4be862466d5cb3f4/lib/index.js#L569) line. So some how the html file's content buffer is not true when checked through utf8 method.

Should not be the case where the contents are automatically converted to utf-8 if they are .html files? Why the check for isUtf8?

I don't what could be making this fuss, but I am stuck here in my project work.

**Comment by webketje** [comment]
Hi there,

Nothing does an "automatic utf-8 conversion". Having a `<meta charset="utf-8">` tag does not convert the document to utf-8, it only informs the browser that the document should be interpreted as utf-8. 

Metalsmith does a utf-8 check to know if the file is a text file or a binary file because binary files like images cannot contain front-matter and they need to be skipped. There are [a lot of character encodings](https://en.wikipedia.org/wiki/Character_encoding#Common_character_encodings) but UTF-8 is the most widely used and safe to detect.

So in this case either/or:
- Redoc generates your metalsmith source files in a non-utf-8 encoding. You can check this by opening the document with an editor like Notepad++ which has charset re-encoding support. If I'm not mistaken (but I should test) Notepad on some Windows versions also saves text files as non-UTF8 by default (so if you opened a file with Notepad & saved it in another encoding without knowing it, the build will fail.
- Redoc generates files with NULL-terminated strings for which there is a known bug in the `is-utf8`  package: https://github.com/wayfind/is-utf8/issues/6

**Comment by webketje** [comment]
Closing as stale, feel free to comment if it needs to be reopened

**Comment by gargi91** [comment]
Hey,

Thanks for your response. 

After a little deep dive, I figured out a way. I found another library `utf-8-validate` to validate the source files. This library works well with all the source files I had including the one I generated from Redoc.

So, basically I created a plugin called frontmatterParser which will use this `utf-8-validate` library instead of `is-utf8` library and to use my plugin I set the property `frontmatter` to false. This solved my problem.
